name: Action for Spring Boot backend

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Copy secret file
        run: printf "%s" "${{ secrets.SPRING_BOOT_APPLICATION_SECRET }}" > backend/butter/src/main/resources/application-secret.yml
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper and build with Gradle
        run: cd backend/butter; chmod +x ./gradlew; ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: cd backend/butter; docker build -t butter-spring-boot-backend:latest .

      - name: Push Docker Image to Docker Hub
        run: cd backend/butter; docker push ${{ secrets.DOCKER_HUB_USERNAME }}/butter-spring-boot-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker stop butter-spring-boot-backend || true
            docker rm butter-spring-boot-backend || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/butter-spring-boot-backend:latest
            docker run -d --name my-app -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/butter-spring-boot-backend:latest
